### ISSUE TITLE
Bamview issue

### ISSUE THREAD

**Issue by fanx772** [sanger-pathogens/Artemis#295] opened 2019-08-18 20:00 UTC
I just use Bamview and downloaded it in both linux (redhat) and window. In the linux, it could not be opened. In the window (10), it could be opened but closed automatically when loading a bam file. 

Error message in linux: fanx@im-drc2-141mn4 ~]$ java -jar BamView_v1.2.11.jar
log4j:WARN No appenders could be found for logger (uk.ac.sanger.artemis.components.alignment.BamView).
log4j:WARN Please initialize the log4j system properly.
Exception in thread "main" java.lang.IllegalArgumentException: invalid range properties
                at javax.swing.DefaultBoundedRangeModel.<init>(DefaultBoundedRangeModel.java:102)
                at javax.swing.JScrollBar.<init>(JScrollBar.java:158)
                at uk.ac.sanger.artemis.components.alignment.BamView.addBamToPanel(BamView.java:2398)
                 at uk.ac.sanger.artemis.components.alignment.BamView.<init>(BamView.java:381)
                 at uk.ac.sanger.artemis.components.alignment.BamView.main(BamView.java:4394)

Can you help to solve this issue? Thanks

**Comment by fanx772** [comment] 2019-08-18 20:12
btw, bamview was run with java 11 in both linux and window. Thanks

**Comment by kpepper** [comment] 2019-08-19 08:17
Hi **@fanx772**. As you've raised an artemis-help ticket as well, we'll deal with the problem through that. Hence, I'll close this issue. 
- Duplicate of RT 668106.

**Closed by kpepper** 2019-08-19 08:17 UTC
